spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=
spring.redis.database=0
spring.redis.timeout=3000
spring.redis.pool.max-active=100
spring.redis.pool.max-idle=20
spring.redis.pool.max-wait-millis=15000